CI: Add sanitizer nighty builds/tests

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -920,3 +920,101 @@ Coverage Report:
       cobertura: coverage.xml
     paths:
       - coverage-html
+
+.sanitizer-common-nigtly:
+  stage: test
+  extends: .common-nightly
+  parallel: 20
+  variables:
+    LIBAOM_TEST_DATA_PATH: ${CI_PROJECT_DIR}/libaom-test-data
+    GTEST_TOTAL_SHARDS: ${CI_NODE_TOTAL}
+    GTEST_OUTPUT: "xml:report.xml"
+    SANITIZER_OPTIONS: "\
+     :handle_segv=1\
+     :handle_abort=1\
+     :handle_sigfpe=1\
+     :fast_unwind_on_fatal=1\
+     :allocator_may_return_null=1"
+  before_script:
+    - export PATH="/usr/lib/llvm-6.0/bin:${PATH}"
+    - export GTEST_SHARD_INDEX=$((CI_NODE_INDEX - 1))
+  script:
+    - |
+      case $AOM_SANITIZER_TYPE in
+        address)
+          SANITIZER_OPTIONS="${SANITIZER_OPTIONS}:detect_stack_use_after_return=1"
+          SANITIZER_OPTIONS="${SANITIZER_OPTIONS}:max_uar_stack_size_log=17"
+          export ASAN_OPTIONS="${SANITIZER_OPTIONS}"
+          ;;
+        memory)
+          export MSAN_OPTIONS="${SANITIZER_OPTIONS}"
+          ;;
+        thread)
+          # The thread sanitizer uses a subset.
+          TSAN_OPTIONS="handle_sigfpe=1"
+          TSAN_OPTIONS="$TSAN_OPTIONS handle_segv=1"
+          TSAN_OPTIONS="$TSAN_OPTIONS handle_abort=1"
+          export TSAN_OPTIONS
+          ;;
+        undefined|integer)
+          SANITIZER_OPTIONS="${SANITIZER_OPTIONS}:print_stacktrace=1:suppressions=.gitlab/UBSan.supp"
+          export UBSAN_OPTIONS="${SANITIZER_OPTIONS}"
+          ;;
+      esac
+    - |
+      filter="*Large*"
+      # As of 17 May 2018 there are no large threading tests.
+      [ "${sanitizer}" = "thread" ] && filter="*Thread*Large*" || :
+    - ./aom_build/${AOM_SANITIZER_TYPE}/test_libaom --gtest_filter="${filter}" 2> >(tee -a sanitizer.log >&2)
+    - |
+      # Looking for sanitizer output in log...
+      grep -q "\(ERROR\|WARNING\): \(Address\|Thread\|Memory\|Leak\)Sanitizer:" sanitizer.log && {
+        echo "Found sanitizer errors or warnings, check the log:"
+        cat sanitizer.log
+        exit 1
+      }
+      # Looking for UBSan output in log (differs from the common format)
+      grep -q ":[[:digit:]]\+:[[:digit:]]\+: runtime error:" sanitizer.log && {
+        echo "Found sanitizer errors or warnings, check the log:"
+        cat sanitizer.log
+        exit 1
+      }
+      echo "No sanitizer errors found"
+  artifacts:
+    expose_as: 'Nightly sanitizer logs'
+    name: "sanitizer.log-$CI_JOB_ID"
+    when: on_failure
+    paths:
+      - sanitizer.log
+
+Linux Sanitizer (address) Test Nightly:
+  extends: .sanitizer-common-nigtly
+  variables:
+    AOM_SANITIZER_TYPE: address
+  needs:
+    - 'Test Data'
+    - 'Linux Sanitizers (x86_64-clang): [address]'
+
+Linux Sanitizer (undefined) Test Nightly:
+  extends: .sanitizer-common-nigtly
+  variables:
+    AOM_SANITIZER_TYPE: undefined
+  needs:
+    - 'Test Data'
+    - 'Linux Sanitizers (x86_64-clang): [undefined]'
+
+Linux Sanitizer (integer) Test Nightly:
+  extends: .sanitizer-common-nigtly
+  variables:
+    AOM_SANITIZER_TYPE: integer
+  needs:
+    - 'Test Data'
+    - 'Linux Sanitizers (x86_64-clang): [integer]'
+
+Linux Sanitizer (thread) Test Nightly:
+  extends: .sanitizer-common-nigtly
+  variables:
+    AOM_SANITIZER_TYPE: thread
+  needs:
+    - 'Test Data'
+    - 'Linux Sanitizers (x86_64-clang): [thread]'
